[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.htlm"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.production.environment]
NEXT_SERVERLESS = "true"
NODE_ENV = "production"